#!/bin/bash

#
# Watches given folder(s) and runs a given command when something changes.
# Does not support aliases as it uses xargs.
#
# Author: Frank de Graaf (Phally)
# License: MIT
#
# Usage:
# watchdo <folder ...> -- <command>
#
# Maybe later:
# - Ability to pass the excludes also.
#

watch="fswatch -0 -e \"~$\" -r"
xargs="xargs -0 -I {}";

folders=true
for var in "$@";
do
    if [ "${var}" == "--" ]
    then
        folders=false
    elif [ $folders = true ]
    then
        watch="${watch} ${var}"
    else
        cmd="${cmd}${var} "
    fi
done

if [ -z "$cmd" ]
then
>&2 echo "Usage: watchdo <folder ...> -- <command>"
>&2 echo "No command to execute."
exit 1
fi

cmd="${watch} | ${xargs} ${cmd}"
echo "Full command: ${cmd}";
echo
eval "$cmd"
